# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-21 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['Nombre_producto']},
        ),
    ]
