# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-02 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20190425_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
