# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre_categoria',
            field=models.CharField(help_text='Describa la Categoria', max_length=100, unique=True),
        ),
    ]
