# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-12 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('Precio_unidad', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_de_vencimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_de_Compra', models.PositiveIntegerField(unique=True)),
                ('Responsable', models.CharField(max_length=150)),
                ('Cortesia', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='Nro_de_Compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento.Orden'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
