# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0006_auto_20190509_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('Precio_unidad', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_de_vencimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_de_Compra', models.PositiveIntegerField(unique=True)),
                ('Responsable', models.CharField(max_length=150)),
                ('Cortesia', models.TextField(blank=True, help_text='Describa las cortesias que se ingreso.', null=True)),
                ('Total_paquetes', models.IntegerField(blank=True, null=True)),
                ('Total_sin_descuento', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('toto_pago', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingreso', models.ManyToManyField(blank=True, null=True, to='movimiento.IngresoProducto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('Kilometraje', models.PositiveIntegerField(blank=True, help_text='Opcional', null=True)),
                ('estado', models.BooleanField(default=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Metas', models.FloatField(blank=True, null=True)),
                ('Avanse', models.FloatField(blank=True, null=True)),
                ('Porsentaje', models.FloatField(blank=True, null=True)),
                ('Total_a_pagar', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('Precio_venta', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=10, unique=True)),
                ('Movil', models.PositiveIntegerField(unique=True)),
                ('Kilometraja', models.IntegerField(blank=True, help_text='Opcional', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('Conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='Movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento.Vehiculo'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='salida',
            name='Movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento.Vehiculo'),
        ),
        migrations.AddField(
            model_name='salida',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salida',
            name='salidas',
            field=models.ManyToManyField(blank=True, null=True, to='movimiento.SalidaProducto'),
        ),
    ]
