# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoproducto',
            name='proveedor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='producto.Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='Cortesia',
            field=models.TextField(blank=True, help_text='Describa las cortesias que se ingreso.', null=True),
        ),
    ]
