# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20190321_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimiento', '0004_ingresoproducto_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('Precio_venta', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.PositiveIntegerField(unique=True)),
                ('Movil', models.PositiveIntegerField(unique=True)),
                ('Kilometraja', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('Conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='Movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimiento.Vehiculo'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
