# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0006_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
