# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0007_salida_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='Avanse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='Metas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='Porsentaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='Total_a_pagar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
