# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-25 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0009_auto_20190402_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproducto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='Kilometraje',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional', null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='Kilometraja',
            field=models.IntegerField(blank=True, help_text='Opcional', null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
