# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-10 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
